security:
    encoders:
        Dsnet\UserBundle\Entity\SystemUser: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Dsnet\UserBundle\Entity\SystemUser
                property: email

    firewalls:
        secured_area:
            form_login:
                csrf_provider: form.csrf_provider
                login_path: /
                check_path: /login_check
            pattern:      ^/
            logout:
                path:   /logout
                target: /
            anonymous:    true
            oauth:        true

            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
