<?php

namespace Dsnet\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SystemUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemUserRepository extends EntityRepository
{
}
